name: Nightly iceoryx run

on:
  schedule:
  - cron: "0 6 * * 1-5"
  push:
    branches: [ master ]

jobs:
  build-test-macos:
    runs-on: macos-10.15
    # prevent stuck jobs consuming macos runners for 6 hours
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2
      - run: ./tools/ci/build-test-macos.sh