# codecov yaml

codecov:
  require_ci_to_pass: yes

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: yes
  require_base: yes
  require_head: yes

coverage:
  range: 70..100
  status:
    project:
      default:
        target: 70%
        threshold: 2% # allow coverage to drop maximum by a defined value
        flags:
          - unittest
    patch:
      default:
        target: auto
        threshold: 2% # allow coverage to drop maximum by a defined value
        flags:
          - unittest
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: yes
      macro: yes

fixes:
  - "/home/runner/work/iceoryx/iceoryx/::"
